spring:
  datasource:
    url: jdbc:h2:mem:visita;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8080
