server:
  port: 8080
  # ADICIONE ESTA CONFIGURAÇÃO PARA FORÇAR UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # O restante do arquivo continua igual
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:visita;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false